#ifndef DHTFETCHER_COMMON_CORE_NOTIFICATION_TYPES_H_
#define DHTFETCHER_COMMON_CORE_NOTIFICATION_TYPES_H_

#include "base/basictypes.h"

enum FetcherNotification {
  NOTIFICATION_TYPE_START = 0,
  
  NOTIFICATION_ALL = NOTIFICATION_TYPE_START,
  
  NOTIFICATION_TYPE_END
};

#endif
